export type Availability = "viele_plaetze" | "wenige_plaetze" | "ausgebucht";

export interface Course {
  id: string;
  label: string;
  type: "langgymi" | "kurzgymi";
  location: string;
  day: string;
  time: string;
  startDate: string;
  price: number;
  originalPrice?: number;
  discountUntil?: string;
  availability: Availability;
}

export interface Provider {
  id: string;
  name: string;
  shortDescription?: string;
  shortDescriptionEn?: string;
  logoUrl: string | null;
  score: number;
  price: number | null;
  priceRange?: { min: number; max: number };
  originalPrice?: number;
  discountUntil?: string;
  locations: string[];
  teachingDays: string[];
  availability: Availability;
  quality: 1 | 2 | 3;
  maxParticipants: string;
  websiteUrl: string;
  hasELearning: boolean;
  hasEinstufungstest: boolean;
  hasPruefungsarchiv: boolean;
  hasAufsatzkorrektur: boolean;
  hasLernunterlagen: boolean;
  hasBeratungsgespraech: boolean;
  hasDistanceLearning: boolean;
  hasDigitalMaterials: boolean;
  hasCatchUpOptions: boolean;
  courses: Course[];
}

const mkCourses = (id: string, basePrice: number, locations: string[]): Course[] =>
  locations.slice(0, 3).map((loc, i) => ({
    id: `${id}-c${i}`,
    label: `Kurs ${String.fromCharCode(65 + i)}`,
    type: i % 2 === 0 ? "langgymi" : "kurzgymi",
    location: loc,
    day: ["Mittwoch", "Samstag", "Dienstag"][i % 3],
    time: ["09:00–10:30", "14:00–15:30", "16:30–18:00"][i % 3],
    startDate: ["29.08.2026", "05.09.2026", "12.09.2026"][i % 3],
    price: basePrice + i * 120,
    originalPrice: i === 0 ? basePrice + 200 : undefined,
    discountUntil: i === 0 ? "31.07.2026" : undefined,
    availability: (["viele_plaetze", "wenige_plaetze", "viele_plaetze"] as Availability[])[i % 3],
  }));

export const providers: Provider[] = [
  {
    id: "gymivorbereitung-zuerich",
    name: "Gymivorbereitung Zürich",
    shortDescription: "Premium-Anbieter mit starker Erfolgsbilanz und Online-Optionen.",
    shortDescriptionEn: "Premium provider with strong track record and online options.",
    logoUrl: null,
    score: 93,
    price: 3290,
    originalPrice: 3490,
    discountUntil: "31.07.2026",
    locations: ["Zürich HB", "Stadelhofen", "Oerlikon"],
    teachingDays: ["Mi", "Sa"],
    availability: "viele_plaetze",
    quality: 3,
    maxParticipants: "4–8",
    websiteUrl: "https://example.ch/gymi-zuerich",
    hasELearning: true,
    hasEinstufungstest: true,
    hasPruefungsarchiv: true,
    hasAufsatzkorrektur: true,
    hasLernunterlagen: true,
    hasBeratungsgespraech: true,
    hasDistanceLearning: true,
    hasDigitalMaterials: true,
    hasCatchUpOptions: true,
    courses: mkCourses("gz", 3290, ["Zürich HB", "Stadelhofen", "Oerlikon"]),
  },
  {
    id: "lern-forum",
    name: "Lern-Forum.ch",
    shortDescription: "Etablierter Anbieter mit breitem Standortnetz im Kanton Zürich.",
    shortDescriptionEn: "Established provider with a broad network across Canton Zürich.",
    logoUrl: null,
    score: 88,
    price: 2980,
    locations: ["Zürich HB", "Winterthur", "Uster", "Wetzikon"],
    teachingDays: ["Di", "Sa"],
    availability: "wenige_plaetze",
    quality: 3,
    maxParticipants: "5–10",
    websiteUrl: "https://example.ch/lernforum",
    hasELearning: true,
    hasEinstufungstest: true,
    hasPruefungsarchiv: true,
    hasAufsatzkorrektur: true,
    hasLernunterlagen: true,
    hasBeratungsgespraech: true,
    hasDistanceLearning: true,
    hasDigitalMaterials: true,
    hasCatchUpOptions: false,
    courses: mkCourses("lf", 2980, ["Zürich HB", "Winterthur", "Uster"]),
  },
  {
    id: "logos",
    name: "Logos Lehrerteam",
    shortDescription: "Erfahrenes Lehrerteam, fokussiert auf Mathematik und Deutsch.",
    shortDescriptionEn: "Experienced teaching team focused on Math and German.",
    logoUrl: null,
    score: 84,
    price: 2790,
    locations: ["Zürich HB", "Küsnacht"],
    teachingDays: ["Mi", "Sa"],
    availability: "viele_plaetze",
    quality: 3,
    maxParticipants: "4–8",
    websiteUrl: "https://example.ch/logos",
    hasELearning: false,
    hasEinstufungstest: true,
    hasPruefungsarchiv: true,
    hasAufsatzkorrektur: true,
    hasLernunterlagen: true,
    hasBeratungsgespraech: true,
    hasDistanceLearning: false,
    hasDigitalMaterials: true,
    hasCatchUpOptions: true,
    courses: mkCourses("lo", 2790, ["Zürich HB", "Küsnacht"]),
  },
  {
    id: "fokus",
    name: "Gymivorbereitung-Fokus",
    shortDescription: "Kleine Klassen, intensive Vorbereitung in Zürich Stadt.",
    shortDescriptionEn: "Small classes with intensive preparation in Zürich city.",
    logoUrl: null,
    score: 80,
    price: 3490,
    locations: ["Zürich HB", "Stadelhofen"],
    teachingDays: ["Sa"],
    availability: "wenige_plaetze",
    quality: 3,
    maxParticipants: "3–6",
    websiteUrl: "https://example.ch/fokus",
    hasELearning: true,
    hasEinstufungstest: true,
    hasPruefungsarchiv: true,
    hasAufsatzkorrektur: true,
    hasLernunterlagen: true,
    hasBeratungsgespraech: false,
    hasDistanceLearning: true,
    hasDigitalMaterials: true,
    hasCatchUpOptions: true,
    courses: mkCourses("fo", 3490, ["Zürich HB", "Stadelhofen"]),
  },
  {
    id: "avidii",
    name: "avidii Gymivorbereitung",
    shortDescription: "Reine Online-Vorbereitung mit persönlichem Coaching.",
    shortDescriptionEn: "Fully online preparation with one-on-one coaching.",
    logoUrl: null,
    score: 76,
    price: 2490,
    locations: ["Online"],
    teachingDays: ["flexibel"],
    availability: "viele_plaetze",
    quality: 2,
    maxParticipants: "1:1",
    websiteUrl: "https://example.ch/avidii",
    hasELearning: true,
    hasEinstufungstest: true,
    hasPruefungsarchiv: false,
    hasAufsatzkorrektur: true,
    hasLernunterlagen: true,
    hasBeratungsgespraech: true,
    hasDistanceLearning: true,
    hasDigitalMaterials: true,
    hasCatchUpOptions: true,
    courses: mkCourses("av", 2490, ["Online", "Online", "Online"]),
  },
  {
    id: "learning-culture",
    name: "Learning Culture",
    shortDescription: "Modernes Lernkonzept mit Fokus auf Methodenkompetenz.",
    shortDescriptionEn: "Modern learning concept focusing on methodology.",
    logoUrl: null,
    score: 73,
    price: 2890,
    locations: ["Zürich HB", "Dübendorf"],
    teachingDays: ["Mi", "Sa"],
    availability: "viele_plaetze",
    quality: 2,
    maxParticipants: "5–9",
    websiteUrl: "https://example.ch/learning-culture",
    hasELearning: true,
    hasEinstufungstest: false,
    hasPruefungsarchiv: true,
    hasAufsatzkorrektur: true,
    hasLernunterlagen: true,
    hasBeratungsgespraech: true,
    hasDistanceLearning: true,
    hasDigitalMaterials: true,
    hasCatchUpOptions: false,
    courses: mkCourses("lc", 2890, ["Zürich HB", "Dübendorf"]),
  },
  {
    id: "learningcube",
    name: "LearningCube",
    shortDescription: "App-gestützte Vorbereitung mit Präsenzblöcken.",
    shortDescriptionEn: "App-supported preparation with in-person blocks.",
    logoUrl: null,
    score: 70,
    price: 2390,
    locations: ["Zürich HB", "Bülach"],
    teachingDays: ["Sa"],
    availability: "viele_plaetze",
    quality: 2,
    maxParticipants: "6–10",
    websiteUrl: "https://example.ch/learningcube",
    hasELearning: true,
    hasEinstufungstest: true,
    hasPruefungsarchiv: false,
    hasAufsatzkorrektur: false,
    hasLernunterlagen: true,
    hasBeratungsgespraech: false,
    hasDistanceLearning: true,
    hasDigitalMaterials: true,
    hasCatchUpOptions: true,
    courses: mkCourses("lcu", 2390, ["Zürich HB", "Bülach"]),
  },
  {
    id: "liechti",
    name: "Liechti Akademie",
    shortDescription: "Traditionsreiche Akademie mit individueller Betreuung.",
    shortDescriptionEn: "Long-established academy with individual support.",
    logoUrl: null,
    score: 67,
    price: 3190,
    locations: ["Zürich HB", "Au"],
    teachingDays: ["Mi"],
    availability: "wenige_plaetze",
    quality: 2,
    maxParticipants: "4–7",
    websiteUrl: "https://example.ch/liechti",
    hasELearning: false,
    hasEinstufungstest: true,
    hasPruefungsarchiv: true,
    hasAufsatzkorrektur: true,
    hasLernunterlagen: true,
    hasBeratungsgespraech: true,
    hasDistanceLearning: false,
    hasDigitalMaterials: false,
    hasCatchUpOptions: true,
    courses: mkCourses("li", 3190, ["Zürich HB", "Au"]),
  },
  {
    id: "schuelerhilfe",
    name: "Schülerhilfe Zürich",
    shortDescription: "Bekannter Anbieter mit dichtem Filialnetz.",
    shortDescriptionEn: "Well-known provider with a dense branch network.",
    logoUrl: null,
    score: 63,
    price: 1890,
    locations: ["Zürich HB", "Oerlikon", "Urdorf"],
    teachingDays: ["Di", "Do"],
    availability: "viele_plaetze",
    quality: 2,
    maxParticipants: "5–8",
    websiteUrl: "https://example.ch/schuelerhilfe",
    hasELearning: true,
    hasEinstufungstest: false,
    hasPruefungsarchiv: false,
    hasAufsatzkorrektur: false,
    hasLernunterlagen: true,
    hasBeratungsgespraech: true,
    hasDistanceLearning: false,
    hasDigitalMaterials: true,
    hasCatchUpOptions: false,
    courses: mkCourses("sh", 1890, ["Zürich HB", "Oerlikon", "Urdorf"]),
  },
  {
    id: "ksf",
    name: "KSF Schule",
    shortDescription: "Kurs- und Schulungsforum mit Wochenend-Programmen.",
    shortDescriptionEn: "Course and training centre with weekend programmes.",
    logoUrl: null,
    score: 59,
    price: 1590,
    locations: ["Wetzikon"],
    teachingDays: ["Sa"],
    availability: "ausgebucht",
    quality: 1,
    maxParticipants: "8–12",
    websiteUrl: "https://example.ch/ksf",
    hasELearning: false,
    hasEinstufungstest: false,
    hasPruefungsarchiv: true,
    hasAufsatzkorrektur: false,
    hasLernunterlagen: true,
    hasBeratungsgespraech: false,
    hasDistanceLearning: false,
    hasDigitalMaterials: false,
    hasCatchUpOptions: false,
    courses: mkCourses("ks", 1590, ["Wetzikon", "Wetzikon"]),
  },
  {
    id: "progymnasium",
    name: "ProGymnasium",
    shortDescription: "Günstiger Einstieg mit kompakten Kursblöcken.",
    shortDescriptionEn: "Affordable entry with compact course blocks.",
    logoUrl: null,
    score: 55,
    price: 1290,
    locations: ["Bülach", "Dübendorf"],
    teachingDays: ["Sa"],
    availability: "viele_plaetze",
    quality: 1,
    maxParticipants: "8–12",
    websiteUrl: "https://example.ch/progymnasium",
    hasELearning: true,
    hasEinstufungstest: false,
    hasPruefungsarchiv: false,
    hasAufsatzkorrektur: false,
    hasLernunterlagen: true,
    hasBeratungsgespraech: false,
    hasDistanceLearning: true,
    hasDigitalMaterials: true,
    hasCatchUpOptions: false,
    courses: mkCourses("pg", 1290, ["Bülach", "Dübendorf"]),
  },
  {
    id: "akademie-zuerich",
    name: "Akademie Zürich",
    shortDescription: "Klassische Vorbereitung in kleiner Lerngruppe.",
    shortDescriptionEn: "Classic preparation in small learning groups.",
    logoUrl: null,
    score: 51,
    price: 1030,
    locations: ["Zürich HB"],
    teachingDays: ["Mi"],
    availability: "wenige_plaetze",
    quality: 1,
    maxParticipants: "6–10",
    websiteUrl: "https://example.ch/akademie-zuerich",
    hasELearning: false,
    hasEinstufungstest: false,
    hasPruefungsarchiv: false,
    hasAufsatzkorrektur: false,
    hasLernunterlagen: true,
    hasBeratungsgespraech: false,
    hasDistanceLearning: false,
    hasDigitalMaterials: false,
    hasCatchUpOptions: false,
    courses: mkCourses("az", 1030, ["Zürich HB", "Zürich HB"]),
  },
];

export const totalCourses = providers.reduce((sum, p) => sum + p.courses.length, 0);
